wandb_version: 1

activation_function:
  value: SiLU
batch_norm:
  value: false
batch_size:
  value: 32
data_augmentation:
  value: false
dense_size:
  value: 256
dropout:
  value: 0.3
filter_multiplier:
  value: 1
filter_size:
  value: 7
num_filters:
  value: 16
