wandb_version: 1

activation_function:
  value: GELU
batch_norm:
  value: 'No'
batch_size:
  value: 32
data_augmentation:
  value: 'no'
dense_size:
  value: 256
dropout:
  value: 0.2
filter_multiplier:
  value: 2
filter_size:
  value: 5
num_filters:
  value: 8
