wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712500179.0
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.12.2
      5: 0.16.6
      8:
      - 1
      - 5
      13: darwin-arm64
