wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712464117.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.12.2
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
activation_function:
  desc: null
  value: GELU
batch_norm:
  desc: null
  value: 'No'
batch_size:
  desc: null
  value: 32
data_augmentation:
  desc: null
  value: 'no'
dense_size:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.2
filter_multiplier:
  desc: null
  value: 2
filter_size:
  desc: null
  value: 5
num_filters:
  desc: null
  value: 8
