wandb_version: 1

activation_function:
  value: ReLU
batch_norm:
  value: true
batch_size:
  value: 32
data_augmentation:
  value: true
dense_size:
  value: 256
dropout:
  value: 0.3
filter_multiplier:
  value: 0.5
filter_size:
  value: 7
num_filters:
  value: 16
