wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712257010.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.12.2
      5: 0.16.4
      8:
      - 4
      - 5
      13: darwin-arm64
activation_function:
  desc: null
  value: ReLU
batch_norm:
  desc: null
  value: true
batch_size:
  desc: null
  value: 32
data_augmentation:
  desc: null
  value: true
dense_size:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.3
filter_multiplier:
  desc: null
  value: 0.5
filter_size:
  desc: null
  value: 7
num_filters:
  desc: null
  value: 16
